// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB927J-cQ8c940QWDIYY66tZnB_-Mz_PtI',
    appId: '1:102382076469:web:82a9ef71dc85f988b3a77c',
    messagingSenderId: '102382076469',
    projectId: 'lowcarbon-7bc46',
    authDomain: 'lowcarbon-7bc46.firebaseapp.com',
    storageBucket: 'lowcarbon-7bc46.firebasestorage.app',
    measurementId: 'G-PX71Y3L2ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAW34vLW-0f5ZPlHcVJlb4Ku8uwVKUlE',
    appId: '1:102382076469:android:ac4b6ada518c42a8b3a77c',
    messagingSenderId: '102382076469',
    projectId: 'lowcarbon-7bc46',
    storageBucket: 'lowcarbon-7bc46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5L-yvf77vfOq8H9kydTDkddoB5JKCbc',
    appId: '1:102382076469:ios:c5c83d93527f20b9b3a77c',
    messagingSenderId: '102382076469',
    projectId: 'lowcarbon-7bc46',
    storageBucket: 'lowcarbon-7bc46.firebasestorage.app',
    iosBundleId: 'com.example.lowCarbonCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu5L-yvf77vfOq8H9kydTDkddoB5JKCbc',
    appId: '1:102382076469:ios:c5c83d93527f20b9b3a77c',
    messagingSenderId: '102382076469',
    projectId: 'lowcarbon-7bc46',
    storageBucket: 'lowcarbon-7bc46.firebasestorage.app',
    iosBundleId: 'com.example.lowCarbonCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB927J-cQ8c940QWDIYY66tZnB_-Mz_PtI',
    appId: '1:102382076469:web:ab2ed96f1bd8ad73b3a77c',
    messagingSenderId: '102382076469',
    projectId: 'lowcarbon-7bc46',
    authDomain: 'lowcarbon-7bc46.firebaseapp.com',
    storageBucket: 'lowcarbon-7bc46.firebasestorage.app',
    measurementId: 'G-WNBJH5MNJM',
  );
}
